import Anthropic from "@anthropic-ai/sdk";
import { type Effort } from "./pipeline/models";
import { type Usage, type UsageSink } from "./spend/pricing";

// Which upstream serves a run's model calls. "anthropic" is the house default;
// "openrouter" is the BYOK path for visitors with an OpenRouter key (sk-or-…).
export type ModelProvider = "anthropic" | "openrouter";

// OpenRouter's Anthropic-compatible Messages endpoint ("Anthropic skin"): the
// SDK appends /v1/messages to this base. Auth is a Bearer token (the sk-or-
// key), NOT x-api-key — hence authToken below with apiKey nulled, mirroring
// OpenRouter's own Claude Code setup (ANTHROPIC_AUTH_TOKEN + empty API key).
const OPENROUTER_BASE_URL = "https://openrouter.ai/api";

// The provider a client was constructed for — read back by call() to map the
// canonical model name to the provider's wire slug without changing any call
// site's signature.
const clientProvider = new WeakMap<Anthropic, ModelProvider>();

export function providerOf(client: Anthropic): ModelProvider {
  return clientProvider.get(client) ?? "anthropic";
}

// Canonical model id → OpenRouter slug. OpenRouter uses DOTTED minor versions
// (anthropic/claude-opus-4.8) but plain names for unversioned models
// (anthropic/claude-sonnet-5) — verified against GET /api/v1/models.
const OPENROUTER_SLUGS: Record<string, string> = {
  "claude-sonnet-5": "anthropic/claude-sonnet-5",
  "claude-opus-4-8": "anthropic/claude-opus-4.8",
  "claude-sonnet-4-6": "anthropic/claude-sonnet-4.6",
  "claude-haiku-4-5": "anthropic/claude-haiku-4.5",
};

/** Map a canonical Anthropic model id to the wire id for the given provider.
 * Internal records (agent_runs, cost ledger, events) always keep the
 * canonical name; only the outgoing request body carries the slug. */
export function wireModel(model: string, provider: ModelProvider): string {
  if (provider !== "openrouter") return model;
  return OPENROUTER_SLUGS[model] ?? `anthropic/${model.replace(/-(\d+)-(\d+)$/, "-$1.$2")}`;
}

// Client factory. Key resolution: explicit per-run key (BYOK seam) → server env.
// AI Gateway swap point: to route spend through Vercel AI Gateway, set baseURL +
// the gateway key here once the web_search passthrough is verified (PLAN §12).
export function getClient(apiKey?: string, provider: ModelProvider = "anthropic"): Anthropic {
  if (provider === "openrouter") {
    if (!apiKey) throw new Error("No OpenRouter API key provided for this run.");
    const client = new Anthropic({ authToken: apiKey, apiKey: null, baseURL: OPENROUTER_BASE_URL });
    clientProvider.set(client, "openrouter");
    return client;
  }
  const key = apiKey || process.env.ANTHROPIC_API_KEY;
  if (!key) throw new Error("No Anthropic API key configured (set ANTHROPIC_API_KEY or pass one per run).");
  return new Anthropic({ apiKey: key });
}

// Minimal param surface we use. Cast to the SDK type at the call site so beta-ish
// fields (output_config.effort, adaptive thinking, web_search_20260209) don't
// fight version drift in the SDK's exported param types.
export interface CallParams {
  model: string;
  max_tokens: number;
  system?: string;
  messages: Anthropic.MessageParam[];
  tools?: unknown[];
  effort?: Effort;
  jsonSchema?: Record<string, unknown>; // structured output
  adaptiveThinking?: boolean;
  // Container id from a prior response's `container` field. REQUIRED on any
  // continuation of a turn whose server tools (web_search_20260209) ran in a
  // code-execution container and left a pending client tool_use — omitting it
  // makes the API reject the continuation with a 400 ("container_id is
  // required when there are pending tool uses generated by code execution").
  container?: string;
}

export interface CallOptions {
  maxPauseResumes?: number; // server-tool (web search) pause_turn resumes
  onText?: (delta: string) => void; // streamed text deltas (Stage A live feed)
  /** Tool activity note + a present-participle verb ("searching", "reading"). */
  onToolNote?: (note: string, verb?: string) => void;
  /** Raw generation deltas while the model streams (live activity feed). */
  onProgress?: (kind: "text" | "thinking", delta: string) => void;
  onUsage?: UsageSink; // token usage → spend ledger / kill-switch
  signal?: AbortSignal; // true request-level abort (factory cancel/timeout)
}

// ---- Prompt caching --------------------------------------------------------
// The prefix renders tools → system → messages; a breakpoint on the system
// block therefore caches tools + system together. We add at most three
// ephemeral breakpoints per request (max allowed is 4): last custom tool,
// system, and the last user message — the last one is what lets pause_turn
// resumes and multi-turn tool loops re-read the conversation prefix instead of
// reprocessing it at full input price every round. Inputs are never mutated;
// annotated copies are built per request.
const EPHEMERAL = { type: "ephemeral" } as const;

function annotateToolsForCache(tools: unknown[]): unknown[] {
  if (!tools.length) return tools;
  const last = tools[tools.length - 1] as { input_schema?: unknown; cache_control?: unknown } | null;
  // Only annotate plain custom tool definitions; server tools (web_search_*,
  // code_execution_*) keep their exact wire shape.
  if (!last || typeof last !== "object" || last.cache_control || !last.input_schema) return tools;
  return [...tools.slice(0, -1), { ...last, cache_control: EPHEMERAL }];
}

function annotateMessagesForCache(messages: Anthropic.MessageParam[]): Anthropic.MessageParam[] {
  for (let i = messages.length - 1; i >= 0; i--) {
    const m = messages[i];
    if (m.role !== "user") continue;
    if (typeof m.content === "string") {
      if (!m.content.trim()) return messages;
      const annotated: Anthropic.MessageParam = {
        ...m,
        content: [{ type: "text", text: m.content, cache_control: EPHEMERAL }],
      };
      return [...messages.slice(0, i), annotated, ...messages.slice(i + 1)];
    }
    if (Array.isArray(m.content)) {
      for (let j = m.content.length - 1; j >= 0; j--) {
        const b = m.content[j] as { type?: string; text?: string; cache_control?: unknown };
        if (!b || b.cache_control) return messages;
        // Only text / tool_result blocks accept cache_control; skip others.
        if (b.type !== "text" && b.type !== "tool_result") continue;
        if (b.type === "text" && !(b.text ?? "").trim()) continue;
        const blocks = [...m.content];
        blocks[j] = { ...(b as object), cache_control: EPHEMERAL } as (typeof blocks)[number];
        return [...messages.slice(0, i), { ...m, content: blocks }, ...messages.slice(i + 1)];
      }
    }
    return messages; // last user message has no annotatable block
  }
  return messages;
}

function buildParams(p: CallParams): Record<string, unknown> {
  const output_config: Record<string, unknown> = {};
  if (p.effort) output_config.effort = p.effort;
  if (p.jsonSchema) output_config.format = { type: "json_schema", schema: p.jsonSchema };
  const params: Record<string, unknown> = {
    model: p.model,
    max_tokens: p.max_tokens,
    messages: annotateMessagesForCache(p.messages),
  };
  // System as a text block so it can carry the cache breakpoint (caches the
  // tools + system prefix together — see note above buildParams helpers).
  if (p.system) params.system = [{ type: "text", text: p.system, cache_control: EPHEMERAL }];
  if (p.tools) params.tools = annotateToolsForCache(p.tools);
  if (p.container) params.container = p.container;
  if (Object.keys(output_config).length) params.output_config = output_config;
  // Sonnet 5 runs adaptive by default; Opus needs it set explicitly. Haiku 4.5
  // does not support adaptive thinking, so callers omit it. display:summarized
  // opts back into readable thinking text (default is omitted on current
  // models) so the live activity feed can surface "Thinking: …" snippets —
  // display affects visibility only, never billing.
  if (p.adaptiveThinking) params.thinking = { type: "adaptive", display: "summarized" };
  return params;
}

// One streamed call, resuming server-tool pauses, returning the final Message.
async function streamOnce(
  client: Anthropic,
  params: Record<string, unknown>,
  opts: CallOptions,
): Promise<Anthropic.Message> {
  const stream = client.messages.stream(
    params as unknown as Anthropic.MessageStreamParams,
    opts.signal ? { signal: opts.signal } : undefined,
  );
  // Harvest the code-execution container id from RAW wire events. The SDK's
  // stream accumulator seeds its snapshot from message_start but drops every
  // message_delta field except stop_reason/stop_details/usage — so a container
  // id delivered mid-turn (when server-side code execution spins up, e.g.
  // web_search_20260209 dynamic filtering) never reaches finalMessage().
  // Without it, continuing a turn that has a pending code-exec tool use 400s:
  // "container_id is required when there are pending tool uses generated by
  // code execution with tools."
  let containerFromWire: string | undefined;
  stream.on("streamEvent", (event) => {
    const e = event as {
      type?: string;
      container?: { id?: string };
      message?: { container?: { id?: string } };
      delta?: { container?: { id?: string } };
    };
    containerFromWire =
      e.message?.container?.id ?? e.delta?.container?.id ?? e.container?.id ?? containerFromWire;
  });
  // TEMPORARY diagnostic tap (env-gated): dump message-level wire events so we
  // can see fields the SDK's stream accumulator drops (e.g. `container` on
  // message_delta). No-op unless FACTORY_DIAG_STREAM=1.
  if (process.env.FACTORY_DIAG_STREAM === "1") {
    stream.on("streamEvent", (event) => {
      const t = (event as { type: string }).type;
      if (t === "message_start" || t === "message_delta" || t === "message_stop") {
        console.error(`[FACTORY_DIAG_STREAM] ${JSON.stringify(event).slice(0, 1500)}`);
      } else if (t === "content_block_start") {
        const cb = (event as { content_block?: { type?: string; name?: string; caller?: unknown } }).content_block;
        console.error(
          `[FACTORY_DIAG_STREAM] block ${cb?.type} ${cb?.name ?? ""} caller=${JSON.stringify(cb?.caller ?? null)}`,
        );
      }
    });
  }
  if (opts.onText) stream.on("text", (delta: string) => opts.onText!(delta));
  if (opts.onToolNote || opts.onProgress) {
    // Server-tool inputs stream as input_json_delta fragments on the block's
    // index; accumulate them so the note can carry the real search query. The
    // note fires at content_block_stop, once per tool use, when the input is
    // complete.
    const serverToolInput = new Map<number, { name: string; json: string }>();
    stream.on("streamEvent", (event) => {
      if (event.type === "content_block_start") {
        const cb = event.content_block as { type: string; name?: string };
        if (cb.type === "server_tool_use") {
          serverToolInput.set(event.index, { name: cb.name ?? "", json: "" });
        } else if (cb.type === "web_search_tool_result") {
          opts.onToolNote?.("Reading search results…", "reading");
        }
      } else if (event.type === "content_block_delta") {
        const d = event.delta as { type: string; partial_json?: string; text?: string; thinking?: string };
        if (d.type === "input_json_delta" && typeof d.partial_json === "string") {
          const st = serverToolInput.get(event.index);
          if (st && st.json.length < 4000) st.json += d.partial_json;
        } else if (d.type === "text_delta" && d.text) {
          opts.onProgress?.("text", d.text);
        } else if (d.type === "thinking_delta" && d.thinking) {
          opts.onProgress?.("thinking", d.thinking);
        }
      } else if (event.type === "content_block_stop") {
        const st = serverToolInput.get(event.index);
        if (!st) return;
        serverToolInput.delete(event.index);
        if (!opts.onToolNote) return;
        if (st.name === "web_search") {
          let query = "";
          try {
            const input = JSON.parse(st.json || "{}") as { query?: unknown };
            if (typeof input.query === "string") query = input.query.replace(/\s+/g, " ").trim().slice(0, 140);
          } catch {
            /* incomplete input JSON — fall back to the generic note */
          }
          opts.onToolNote(query ? `Searching: "${query}"` : "Searching the web…", "searching");
        } else {
          opts.onToolNote(`Running ${st.name || "a server tool"}…`, "running");
        }
      }
    });
  }
  const msg = await stream.finalMessage();
  if (containerFromWire && !msg.container) {
    (msg as { container?: unknown }).container = { id: containerFromWire, expires_at: "" };
  }
  return msg;
}

export async function call(
  client: Anthropic,
  p: CallParams,
  opts: CallOptions = {},
): Promise<Anthropic.Message> {
  // Wire-level model slug for the client's provider; p.model stays canonical
  // everywhere else (usage records, cost pricing, agent_runs).
  const base = buildParams({ ...p, model: wireModel(p.model, providerOf(client)) });
  let msg = await streamOnce(client, base, opts);
  opts.onUsage?.(p.model, msg.usage as Usage);
  // The container id (code-execution-backed server tools, e.g. web_search) may
  // arrive on an EARLY pause segment and be null on later ones. Remember it,
  // pass it on every pause resume, and surface it on the returned message so
  // callers that continue this turn (client tool_result rounds) can echo it —
  // without it the API 400s: "container_id is required when there are pending
  // tool uses generated by code execution with tools."
  let containerId: string | undefined = msg.container?.id ?? p.container ?? undefined;
  const maxResumes = opts.maxPauseResumes ?? 3;
  for (let i = 0; i < maxResumes && msg.stop_reason === "pause_turn"; i++) {
    // Re-annotate so the resume carries the same message cache breakpoint as
    // the original request (identical prefix bytes → cache read).
    const messages = annotateMessagesForCache([
      ...(p.messages as Anthropic.MessageParam[]),
      { role: "assistant" as const, content: msg.content },
    ]);
    msg = await streamOnce(client, { ...base, messages, ...(containerId ? { container: containerId } : {}) }, opts);
    opts.onUsage?.(p.model, msg.usage as Usage);
    containerId = msg.container?.id ?? containerId;
  }
  if (msg.stop_reason === "refusal") {
    throw new Error("The request was declined by the model's safety systems.");
  }
  if (containerId && !msg.container) {
    (msg as { container?: unknown }).container = { id: containerId, expires_at: "" };
  }
  return msg;
}

export function textOf(msg: Anthropic.Message): string {
  return (msg.content || [])
    .filter((b): b is Anthropic.TextBlock => b.type === "text")
    .map((b) => b.text)
    .join("\n");
}

// Matches ASCII control chars (U+0000–U+001F) that are illegal inside a JSON
// string. Built via RegExp() so no literal control bytes live in this source.
const CONTROL_CHARS = new RegExp("[\\u0000-\\u001F]", "g");

// Tolerant JSON extraction (mirrors the prototype's parseJSON).
export function parseJSONLoose<T = unknown>(text: string): T {
  try {
    return JSON.parse(text) as T;
  } catch {
    /* fall through to bracket extraction */
  }
  const start = text.indexOf("{");
  const end = text.lastIndexOf("}");
  if (start >= 0 && end > start) {
    const slice = text.slice(start, end + 1);
    try {
      return JSON.parse(slice) as T;
    } catch {
      /* fall through */
    }
    // Last resort: drop stray control characters (a raw newline/tab inside a
    // string is invalid JSON and the most common cause of a parse failure) and
    // retry. CONTROL_CHARS is built without literal control bytes in source.
    try {
      return JSON.parse(slice.replace(CONTROL_CHARS, " ")) as T;
    } catch {
      /* fall through */
    }
  }
  throw new Error("Could not parse JSON from model response");
}
